<a href="https://colab.research.google.com/github/ganonononon/Kaggke_Udemy/blob/main/1_Numpy_exercise%E3%83%86%E3%82%B9%E3%83%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# 1. Numpy Exercise
---

Exercise_1 : Numpyライブラリを np というエイリアスでインポートしてください

In [ ]:
import numpy as np

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>import numpy as np</code>
</details>

Exercise_2 :  [1, 3, 5, ..., 21, 23] の連続する値を持つ1次元のNumpy Array（変数名 arr1）を作成してください

In [ ]:
arr1 = np.arange(1,24,2)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1 = np.arange(1, 24, 2)</code>
</details>

In [ ]:
# 実行して表示
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

Exercise_3 : [0., 0.5, 1, ..., 5.5, 6.] （要素数は13）の連続する値を持つ1次元のNumpy Array（変数名 arr2）を作成してください

In [ ]:
arr2 = np.linspace(0,6,13)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr2 = np.linspace(0, 6, 13)</code><br>
    <code>np.arange(0, 6.1, 0.5)</code>などでも可
</details>

In [ ]:
# 実行して表示
arr2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

Exercise_4 : arr1 を3行4列の配列に変換してください(arr1_reshaped)

In [ ]:
arr1_reshaped = arr1.reshape(3,4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped = arr1.reshape(3, 4)</code>
</details>

In [ ]:
# 実行して表示
arr1_reshaped

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

Exercise_5: arr1 を2次元で1列の配列に変換してください(arr1_1col)

In [ ]:
arr1_1col = arr1.reshape(-1,1)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_1col = arr1.reshape(-1, 1)</code>
</details>

In [ ]:
# 実行して表示
arr1_1col

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23]])

Exercise_6 : arr1 を1次元の配列に変換してください(arr1_1dim)。ただし、arr1を扱っていく一方で、arr1_1dimの値の更新を行っていくことを前提とします。（もとのarr1のデータが変更されない手法を用いる）

In [ ]:
arr1_1dim = arr1.flatten()

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_1dim = arr1.flatten()</code>
    <p>※ ravel()の場合はarr1_1dimを更新するとarr1も更新されてしまうため</p>
</details>

In [ ]:
# 実行して表示
arr1_1dim

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

Exercise_7 : arr1_reshaped の次元数とその形状を確認してください

In [ ]:
# 次元
arr1_reshaped.ndim

2

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped.ndim</code>
</details>

In [ ]:
# 形状
arr1_reshaped.shape

(3, 4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped.shape</code>
</details>

Exercise_8: Numpy の random モジュールを使い、0以上1未満の乱数を5つ持つ一次元の配列を作成してください（arr3）

In [ ]:
arr3 = np.random.rand(5)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr3 = np.random.rand(5)</code>
</details>

In [ ]:
# 実行して表示
arr3

array([0.58463197, 0.00214091, 0.99710451, 0.86292011, 0.81459737])

Exercise_9: 0以上1未満の乱数を持つ2行6列の配列を作成してください（arr4）

In [ ]:
arr4 = np.random.rand(2,6)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr4 = np.random.rand(2, 6)</code>
</details>

In [ ]:
# 実行して表示
arr4

array([[0.81245386, 0.04388986, 0.37447937, 0.94127236, 0.64809   ,
        0.78528272],
       [0.81309549, 0.97620535, 0.47450612, 0.05850021, 0.43804791,
        0.45740487]])

Exercise_10 : 平均が 0、標準偏差が 1 で、正規分布に従う値を持つ3行4列の配列を作成してください （arr5）

In [ ]:
arr5 = np.random.randn(3,4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr5 = np.random.randn(3, 4)</code>
</details>

In [ ]:
# 実行して表示
arr5

array([[ 0.2483625 ,  0.63304972,  1.59643345,  0.64850331],
       [-1.09230412,  0.52960445, -1.69845196,  0.5224056 ],
       [-0.16761865,  0.49508868, -0.30579082, -0.04139909]])

Exercise_11 : arr5 の全要素での、最大値、最小値、平均を確認してください（max_arr5, min_arr5, mean_arr5）

In [ ]:
max_arr5 = arr5.max()
min_arr5 = arr5.min()
mean_arr5 = arr5.mean()
print(f'max : {max_arr5}, min : {min_arr5}, mean : {mean_arr5}')
# 各行ではなく、全体の最大などを取得していることに注意

max : 1.5964334462237024, min : -1.6984519583505582, mean : 0.11399025582009664


<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>max_arr5 = arr5.max()</code><br>
    <code>min_arr5 = arr5.min()</code><br>
    <code>mean_arr5 = arr5.mean()</code>
</details>

Exercise_12: 平均が 100、標準偏差が 10 で、正規分布に従う値を持つ3行4列の配列を作成してください （arr6）

In [ ]:
arr6 = np.random.normal(100,10,(3,4))

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr6 = np.random.normal(100, 10, (3, 4))</code>
</details>

In [ ]:
# 実行して表示
arr6

array([[113.94640363,  90.17882487,  86.20955692, 124.19755842],
       [ 87.73291796,  93.88468544, 100.39093912,  87.38793095],
       [ 98.92066995, 105.68179819,  90.52180737, 110.96259819]])

Exercise_13 : 10 以上 30 未満の値を持つ連続一様分布の3行4列の配列を作成してください （arr7）。また要素全体の平均値が20付近にあることを平均値を求めることで確認してください。

In [ ]:
arr7 = np.random.uniform(10,30,(3,4))

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr7 = np.random.uniform(10, 30, (3, 4))</code>
</details>

In [ ]:
# 実行して表示
arr7

array([[19.21738324, 18.90087006, 27.41402367, 26.21494597],
       [20.6411875 , 28.54100218, 17.32156308, 22.87807669],
       [26.01406799, 18.86671937, 17.50213914, 23.39248048]])

In [ ]:
# 平均値を求める
arr7.mean()
# 20前後の値ならばOK

22.242038280658633

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr7.mean()</code>
</details>

Exercise_14 : arr7 の数値をすべて小数第4位で四捨五入した小数3桁の値に変換してください(arr7_3decimal)

In [ ]:
arr7_3decimal = np.round(arr7,3)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_3decimal = np.round(arr7, 3)</code>
</details>

In [ ]:
# 実行して表示
arr7_3decimal

array([[19.217, 18.901, 27.414, 26.215],
       [20.641, 28.541, 17.322, 22.878],
       [26.014, 18.867, 17.502, 23.392]])

Exercise_15: リスト lis の文字をランダムに10個持つ1次元の配列を作成し（arr8）、データタイプを object に変更してください

In [ ]:
# リストを作成
lis = list('GOOD!')   # ['G', 'O', 'O', 'D', '!']
arr8 = np.random.choice(lis, 10)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr8 = np.random.choice(lis, 10)</code>
</details>

In [ ]:
# 実行して表示
arr8

array(['G', 'D', 'D', '!', '!', '!', 'O', 'O', 'D', '!'], dtype='<U1')

In [ ]:
# データタイプを変更
arr8 = arr8.astype(object)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr8 = arr8.astype(object)</code>
</details>

In [ ]:
# 実行して表示
arr8

array(['G', 'D', 'D', '!', '!', '!', 'O', 'O', 'D', '!'], dtype=object)

Exercise_16 : 次のarr9のデータタイプが 'int32' であることを確認し、その後データタイプを 'float' に変更してください

In [ ]:
# dtypeの確認
arr9 = np.array([1, 3, 5, 7, 9])
arr9.dtype

dtype('int64')

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr9.dtype</code>
</details>

In [ ]:
# floatに変更
arr9 = arr9.astype('float')

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr9.astype(float)</code><br>
</details>

In [ ]:
# 実行して表示
arr9

array([1., 3., 5., 7., 9.])

Exercise_17 : 配列arr10の分散と標準偏差を「計算して」求めてください。また、メソッドを用いてその値が正しいことを確認してください。

In [ ]:
# 実行して表示
np.random.seed(17)
arr10 = np.random.randint(0, 10, 5)
arr10

array([1, 6, 6, 9, 0])

In [ ]:
# 実行して表示
mean = arr10.mean()
mean

4.4

In [ ]:
total = 0
for i in arr10:
    total += (i - mean)**2
total

57.2

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>total += (i - mean)**2</code><br>
</details>

In [ ]:
variance = total / len(arr10)
# 実行して表示
variance

11.440000000000001

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>variance = total / len(arr10)</code><br>
</details>

In [ ]:
standard_deviation = np.sqrt(variance)
# 実行して表示
standard_deviation

3.3823069050575527

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>standard_deviation = np.sqrt(variance)</code><br>
</details>

In [ ]:
# メソッドを使って分散を求める
arr10.var()

11.440000000000001

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr10.var()</code><br>
</details>

In [ ]:
# メソッドを使って標準偏差を求める
arr10.std()

3.3823069050575527

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr10.std()</code><br>
</details>

## 以上